Use `git ls-tree` to list the service start sequence

diff --git a/alterator-etcgit/bin/etcgit-sh-functions b/alterator-etcgit/bin/etcgit-sh-functions
--- a/alterator-etcgit/bin/etcgit-sh-functions
+++ b/alterator-etcgit/bin/etcgit-sh-functions
@@ -354,9 +354,18 @@ _get_runlevel() {
 }
 
 _get_linked_srv() {
-        local srv="$(readlink "$1")"
 
-        echo "${srv##*/}"
+        local srv=
+        
+        if [ -e "$1" ]; then
+                srv="$(readlink "$1")"
+                srv="${srv##*/}"
+        else
+                srv="${1##*/}"
+                srv="${srv#[SK][0-9][0-9]}"
+        fi
+
+        echo "$srv"
 }
 
 _list_rS() {
@@ -390,7 +399,7 @@ _srv_is_independent() {
         fi
 
 	case "$srv" in
-		ahttpd|alteratord|plymouth|local|irqbalance|mdadm|random|udevd|udevd-final|fbsetfont|consolesaver|keytable|gpm|dm|killall|mdadm|messagebus|multipathd|lvm2-monitor|outformat|rawdevices|sysstat|update_wms|x11presetdrv|smartd)
+		ahttpd|ahttpd-firsttime|alteratord|plymouth|local|irqbalance|mdadm|random|udevd|udevd-final|fbsetfont|consolesaver|keytable|gpm|dm|killall|mdadm|messagebus|multipathd|lvm2-monitor|outformat|rawdevices|sysstat|update_wms|x11presetdrv|smartd)
 			return 0
 			;;
 		*)
@@ -401,11 +410,9 @@ _srv_is_independent() {
 
 list_kill_seq_for_srv() {
         local srvname="${1:-$in_service}"
-        local runlevel="$(_get_runlevel)"
-        [ -n "$runlevel" ] || runlevel=3
-        local rcd="/etc/rc.d/rc$runlevel.d"
+        local rcd=/etc/rc.d/rc6.d
         [ -d "$rcd" ] || return 2
-        local klist="$(_list_rS "$rcd")"
+        local klist="$(_list_K "$rcd")"
         local ksrvlist="$(for f in $klist; do ksrv="$(_get_linked_srv "$rcd/$f")"; echo "$ksrv"; [ "$ksrv" != "$srvname" ] || break; done)"
 
 	local ksrvname=
@@ -425,6 +432,19 @@ _list_S() {
 	sort
 }
 
+_list_branch_S_for_runlevel() {
+        local br="${1-$(get_branch_name)}"
+        local runlevel="${2-$(_get_runlevel)}"
+        [ -n "$runlevel" ] || runlevel=3
+
+        (
+                _cd_if_git /etc || exit 0
+                git ls-tree -r --name-only "$br" 2>/dev/null | \
+                sed -n -e "s,^rc\\.d/rc$runlevel\\.d/S,S,p" | \
+                sort
+        )
+}
+
 _srv_is_on() {
         local srv="$1"
         local runlevel=${2-$(_get_runlevel)}
@@ -432,21 +452,25 @@ _srv_is_on() {
         chkconfig --level $runlevel "$srv" 1>/dev/null 2>&1
 }
 
-list_start_seq_for_srv() {
-        local srvname="${1:-$in_service}"
+list_branch_start_seq_for_srv() {
+        local br="${1-$(get_branch_name)}"
+        local srvname="${2:-$in_service}"
         local runlevel="$(_get_runlevel)"
         [ -n "$runlevel" ] || runlevel=3
         local rcd="/etc/rc.d/rc$runlevel.d"
         [ -d "$rcd" ] || return 2
-	local killseq="${2:-$(list_kill_seq_for_srv "$srvname" | _filter_SK)}"
-	[ -n "$killseq" ] || return 0
+	local killseq="$(list_kill_seq_for_srv "$srvname" | _filter_SK)"
+        local slist="$(_list_branch_S_for_runlevel "$br" "$runlevel")"
+        local ssrvlist="$(for f in $slist; do ssrv="$(_get_linked_srv "$rcd/$f")"; echo "$ssrv"; [ "$ssrv" != "$srvname" ] || break; done)"
 
 	local ssrvname=
-        for f in `_list_S "$rcd"`; do
+        for f in $slist; do
 		ssrvname="$(_get_linked_srv "$rcd/$f")"
-                _in_list "$ssrvname" $killseq || continue
-                _srv_is_on "$ssrvname" $runlevel || continue
-                echo "$f"
+                if _in_list "$ssrvname" $killseq; then
+                        echo "$f"
+                elif [ "$ssrvname" == "$srvname" ]; then
+                        echo "$f"
+                fi
         done
 }
 
@@ -499,7 +523,14 @@ list_modified_files() {
         _list_modified "$@" | \
         while read -r status file; do
                 echo "/etc/$file"
-                [ -h "/etc/$file" ] && echo "/etc/${file%/*}/$(readlink "/etc/$file")"
+                case "$file" in
+                        rc.d/rc[0-9].d/[SK]*)
+                                echo "/etc/init.d/${file#rc.d/rc[0-9].d/[SK][0-9][0-9]}"
+                                ;;
+                        *)
+                                [ -h "/etc/$file" ] && echo "/etc/${file%/*}/$(readlink "/etc/$file")"
+                                ;;
+                esac
         done | \
         sort -u
 }
@@ -510,7 +541,8 @@ list_modified_files_and_dirs() {
 }
 
 list_kill_seq() {
-	local srvs="${1-$(_get_service_names_for_files $(list_modified_files_and_dirs "$@"))}"
+        local br="${1-${in_branch-$(get_branch_name)}}"
+	local srvs="$(_get_service_names_for_files $(list_modified_files_and_dirs "$br"))"
 
 	for s in $srvs; do
                 list_kill_seq_for_srv "$s"
@@ -520,11 +552,11 @@ list_kill_seq() {
 }
 
 list_start_seq() {
-	local srvs="${1-$(_get_service_names_for_files $(list_modified_files_and_dirs "$@"))}"
-	local killseq="${2-}"
+        local br="${1-${in_branch-$(get_branch_name)}}"
+	local srvs="$(_get_service_names_for_files $(list_modified_files_and_dirs "$br"))"
 
 	for s in $srvs; do
-                list_start_seq_for_srv "$s" "$killseq"
+                list_branch_start_seq_for_srv "$br" "$s"
         done | \
         sort -u | \
         _filter_SK
@@ -728,17 +760,20 @@ checkout_meta() {
 reload_branch() {
 	local br="${1-${in_branch-$(get_branch_name)}}"
 
-	local srvs="$(_get_service_names_for_files $(list_modified_files_and_dirs "$br"))"
-	local killseq="$(list_kill_seq "$srvs")"
-	local startseq="$(list_start_seq "$srvs" "$killseq")"
+	local killseq="$(list_kill_seq "$br")"
+	local startseq="$(list_start_seq "$br")"
 	local ret=0
 
 	for s in $killseq; do
-		if ! service "$s" condstop >&2 && ! service "$s" stop >&2; then
-                        printf '*** Unable to stop service: %s ***\n' "$s" >&2
-			write_error_message "`_ 'Unable to stop service: %s'`" "$s"
-			ret=1
-			break
+                if chkconfig "$s" 1>/dev/null 2>&1; then
+                        if ! service "$s" condstop >&2 && ! service "$s" stop >&2; then
+                                printf '*** Unable to stop service: %s ***\n' "$s" >&2
+                                write_error_message "`_ 'Unable to stop service: %s'`" "$s"
+                                ret=1
+                                break
+                        fi
+                else
+                        service "$s" condstop >&2 || service "$s" stop >&2
 		fi
 	done
 
